//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticateMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class StudentDetail
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Department { get; set; }
        [Required]
        public int Roll_No { get; set; }
        [Required]
        public int Academic_year { get; set; }
        [Required]
        public int Semester { get; set; }
        [Required]
        public double SSLC_Percentage { get; set; }
        [Required]
        public string SSLC_Marksheet { get; set; }
        [Required]
        public HttpPostedFileBase SSSLFile { get; set; }
        [Required]
        public double HSC_Percentage { get; set; }
        [Required]
        public string HSC_Marksheet { get; set; }
        [Required]
        public HttpPostedFileBase HSCFile { get; set; }
        [Required]
        public double CGPA { get; set; }
        [Required]
        public bool Active_Backlogs { get; set; }
        [Required]
        public int Phone_Number { get; set; }
        [Required]
        public string Personal_Email { get; set; }
        [Required]
        public byte[] Address { get; set; }
        [Required]
        public string Resume { get; set; }
        [Required]
        public HttpPostedFileBase ResumeFile { get; set; }
        [Required]
        public string Photo { get; set; }
        [Required]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
