//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public string Name { get; set; }
        public string Department { get; set; }
        public int Semester { get; set; }
        public double CGPA { get; set; }
        public string Photo { get; set; }
        public int RollNo { get; set; }
        public double SSLC { get; set; }
        public double HSC { get; set; }
        public bool Backlogs { get; set; }
        public int Phonenumber { get; set; }
        public string Emailid { get; set; }
    }
}
